// export { default as AboutProjectPage } from './PageAboutProject'
export { default as LoginPage } from './PageLogin'
export { default as SignUpPage } from './PageSignUp'
export { default as EmailVerifyPage } from './PageEmailVerify'
// export { default as DashboardPage } from './PageDashboard'
